-- Superseded by prisma/migrations/20261006100000_lock_down_public_tables.
--
-- All tables are accessed only through Prisma on the server. That migration
-- enables RLS on every table, drops the old per-user policies and revokes all
-- privileges from the Supabase `anon` and `authenticated` roles, so the public
-- anon key cannot read or write application data.
--
-- When adding a table, add it to a new migration that does the same:
--   ALTER TABLE public.<table> ENABLE ROW LEVEL SECURITY;
--   REVOKE ALL ON public.<table> FROM anon, authenticated;
